#-------------------------------------------------------------------------------
# Docker Environment Composition for a PIDSvc development environment.
#-------------------------------------------------------------------------------
x-postgresql-variables: &postgresql-variables
  POSTGRES_DB: 'ereefs_pidsvc'
  POSTGRES_PASSWORD: 'pidsvc123'
  POSTGRES_USER: 'pidsvc-admin'

volumes:
    dbdata:

services:
    # PostgreSQL database for the PIDSvc Database
    pidsvc-db:
        container_name: pidsvc-db
        image: postgres:14-alpine
        environment:
            <<: [ *postgresql-variables ]
        volumes:
            - dbdata:/var/lib/postgresql/data
            - ./src/main/db/postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql


    # Run this service in the foreground to launch the PIDSvc
    # application in a tomcat servlet container.
    pidsvc-tomcat:
        build:
            context: .
            #target: builder
        container_name: pidsvc-tomcat
        depends_on:
            - pidsvc-db
        environment:
            <<: [ *postgresql-variables ]
            POSTGRES_HOST: 'pidsvc-db'
        image: onaci/pidsvc:dev
        ports:
            - 8080:8080
